# Generated by Django 4.0 on 2021-12-19 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='type',
            field=models.CharField(choices=[('NOR', 'Normal'), ('PLT', 'Plata'), ('ORO', 'Oro'), ('PTN', 'Platino')], default='NOR', max_length=4, verbose_name='Tipo de cliente'),
        ),
        migrations.AlterField(
            model_name='order',
            name='type',
            field=models.CharField(choices=[('CD', 'Centro de distribución'), ('SU', 'Sucursal'), ('EA', 'Empresa asociada')], default='CD', max_length=2, verbose_name='Tipo de pedido'),
        ),
    ]
